<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use App\Traits\CreatedUpdatedBy;

class DataPenduduk extends Model
{
    use HasFactory,CreatedUpdatedBy;

    protected $primaryKey = 'nik';
    protected $fillable = ['nik','nama', 'jenis_kelamin', 'tempat_lahir', 'tanggal_lahir', 'kewarganegaraan', 'agama', 'pekerjaan', 'alamat'];

    public function getFieldAttribute()
    {
        return [
            'nik' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'NIK',
                'form' => 1,
                'form_label' => 'NIK',
                'form_type' => 'text',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'NIK',
                'filter_type' => 'text',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => '',
                'kolom' => 1,
                'sort' => 1,
            ],
            'nama' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Nama',
                'form' => 1,
                'form_label' => 'Nama',
                'form_type' => 'text',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Nama',
                'filter_type' => 'text',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => '',
                'kolom' => 1,
                'sort' => 1,
            ],
            'jenis_kelamin' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Jenis Kelamin',
                'form' => 1,
                'form_label' => 'Jenis Kelamin',
                'form_type' => 'select',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Jenis Kelamin',
                'filter_type' => 'select',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => ['Laki-laki','Perempuan'],
                'kolom' => 1,
                'sort' => 1,
            ],
            'tempat_lahir' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Tempat Lahir',
                'form' => 1,
                'form_label' => 'Tempat Lahir',
                'form_type' => 'text',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Tempat Lahir',
                'filter_type' => 'text',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => '',
                'kolom' => 1,
                'sort' => 1,
            ],
            'tanggal_lahir' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Tanggal Lahir',
                'form' => 1,
                'form_label' => 'Tanggal Lahir',
                'form_type' => 'date',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Tanggal Lahir',
                'filter_type' => 'date',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => '',
                'kolom' => 1,
                'sort' => 1,
            ],
            'kewarganegaraan' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Kewarganegaraan',
                'form' => 1,
                'form_label' => 'Kewarganegaraan',
                'form_type' => 'select',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Kewarganegaraan',
                'filter_type' => 'select',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => ['WNI','WNA'],
                'kolom' => 1,
                'sort' => 1,
            ],
            'agama' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Agama',
                'form' => 1,
                'form_label' => 'Agama',
                'form_type' => 'select',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Agama',
                'filter_type' => 'select',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => ['Islam','Kristen','Katolik','Budha','Hindu','Konghuchu'],
                'kolom' => 1,
                'sort' => 1,
            ],
            'pekerjaan' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Pekerjaan',
                'form' => 1,
                'form_label' => 'Pekerjaan',
                'form_type' => 'text',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Pekerjaan',
                'filter_type' => 'text',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => '',
                'kolom' => 1,
                'sort' => 1,
            ],
            'alamat' => [
                'table' => 1,
                'hidecolom' => 0,
                'label' => 'Alamat',
                'form' => 1,
                'form_label' => 'Alamat',
                'form_type' => 'text',
                'form_required' => 1,
                'filter' => 1,
                'filter_table' => '',
                'filter_label' => 'Alamat',
                'filter_type' => 'text',
                'filter_label_class' => '',
                'filter_form_class' => '',
                'filter_value' => '',
                'keyvaldata' => '',
                'kolom' => 1,
                'sort' => 1,
            ],
            
        ];
    }
}
